##########################################################################
###
### SPATIAL REGRESSION MODELING IN R
### KENTUCKY DEMO 4
### LAST UPDATED APRIL 30, 2011
### RUN SUCCESSFULLY IN R VERSION 2.13.0 ON 5/4/11
###
###########################################################################
###
### SPATIAL REGRESSION MODELING IN R
### IN THIS DEMO WE:
###     1. Read in the shape file and text file data
###     2. Confirm the model we wish to run
###     3. Read in a weights matrix generated by GeoDa software
###     4. Remind ourselves about the OLS model and check the diagnostics
###     5. Run some spatial regression models:
###        a. Spatial error model
###        b. Spatial lag model
###     6. Spatial model estimation using GMM & IV 
###     7. Higher order models
###
###########################################################################
#
# Set working directory:

# setwd("C:/Teaching/Shape Files/Southern Counties Shape file")

# Load the necessary packages:

library(classInt)
library(car)
library(graphicsQC)
library(lmtest)
library(spdep)
library(sp)
library(spatstat)
library(RColorBrewer)

############################################################################
###
### READ IN THE SHAPE FILE
###

soco <- readShapePoly("south00.shp")
summary(soco)    # Nice 6-number summary of each variable

# READ IN THE .txt FILE

socotxt <- read.table('south00.txt', header=T)

# Convert our SpatialPolygonsDataFrame object to a data.frame object
# needed for some of our analysis:

soco.df <- data.frame(soco)

# Add the nice county names from socotxt to soco.df, and rename
# the column "NAME".

soco.df[,1] <- socotxt[,1]
names(soco.df)[1] <- "NAME"
names(soco.df)

### Demos 1 & 2 helped us choose the transformations we wish to use for
### a regression model.  We decided that for purposes of demonstration
### we could be somewhat simple minded about this and present a model
### that predicts child poverty using the county unemployment rate,
### the proportion of female headed families with kids but no spouse,
### and the proportion of persons age 18+ with more than a HS education
### (with all variables transformed as determined in Demos 1 & 2).
### Here we repeat the OLS model developed in Demo 3 and use the
### LaGrange Multiplier statistics to help guide us to an appropriate
### spatial regression specification.  We use the square root
### transformation of PPOV as arrived at in Demo 1 the transformations
### of the independent variables as chosen in Demo 2.

### Attach soco.df as the default data set.

attach(soco.df)
class(soco.df)
names(soco.df)

# Create some new variable names so that R doesn't have to do
# the transformation afresh every time a variable is called upon:

cpov <- sqrt(PPOV)
femhh <- sqrt(PFHH)
unem <- sqrt(PUNEM)
hied <- log(1-PHSLS)

####### READ IN A WEIGHTS MATRIX CREATED IN GEODA AS IN DEMO 3:

socogal <- read.gal("socoQueen1.GAL", override.id=TRUE)
socoQ1.gal <- nb2listw(socogal)

####### RE-RUN THE OLS REGRESSION MODEL FROM DEMO 3:

reg1 <- lm(cpov ~ femhh + unem + hied)
summary(reg1)

#########################################################################
#######
####### WE HAVE PREVIOUSLY SEEN (DEMO 3) THAT THIS REGRESSION HAS SEVERAL
####### POTENTIAL PROBLEMS:
#######    non-normal residuals
#######    heteroskedastickty
#######    non-independent residuals
####### HERE WE EXAMINE, IN PARTICULAR, THE MATTER OF CORRELATED RESIDUALS
#######
##########################################################################

# Run the Moran & Geary tests on the residuals:

moran.test(reg1$residuals, socoQ1.gal, alternative="two.sided")
geary(reg1$residuals, socoQ1.gal, n=length(cpov), n1=length(cpov)-1,
	S0=length(cpov))

####### CLEARLY WE NEED TO MOVE TO A SPATIAL REGRESSION MODEL
####### As we saw in Demo 3: plenty of spatial autocorrelation lurking
####### in the residuals.

# GeoDa-style Lagrange multiplier tests can be obtained using the following.
# These clearly indicate a preference for a spatial error model

lm.LMtests(reg1, nb2listw(socogal), test=c("LMerr", "LMlag", "RLMerr",
"RLMlag", "SARMA"))

#########################################################################
###
############ SPATIAL REGRESSION MODELS
###
#########################################################################

# Spatial lag and spatial error models estimated by maximum likelihood.
# These use the Keith Ord eigenvalue extraction method, and with a
# dataset this size, it takes a while for the models to run.

# First the lag model:

soco.lag.eig <- lagsarlm(cpov ~ femhh + unem + hied,
	data=socotxt, nb2listw(socogal), method="eigen", quiet=FALSE)
summary(soco.lag.eig)

# Now the error model:

soco.err.eig <- errorsarlm(cpov ~ femhh + unem + hied,
	data=socotxt, nb2listw(socogal), method="eigen", quiet=FALSE)
summary(soco.err.eig)

# Sometimes these models can't be run.  It will poop out if it detects
# too high a correlation structure in our X matrix and is unable to
# invert X.  The problem can often be overcome by setting the convergence
# tolerance to a lower value.  The tol.solve DEFAULT = 1.0e-10.  An
# example follows where we use tol.solve=1.0e-15.  But no need to run this
# if the model above ran.

soco.err.eig <- errorsarlm(cpov ~ femhh + unem + hied,
	data=socotxt, nb2listw(socogal), method="eigen", quiet=FALSE,
	tol.solve=1.0e-15)

summary(soco.err.eig)

# Can also try estimating the error model using Kelejian & Prucha's
# generalized moments estimator.  This is estimated differently than the
# the previous models using MLE, and we should anticipate different
# results.  It runs pretty quickly.

socoKP <- GMerrorsar(cpov ~ femhh + unem + hied,
	data=socotxt, nb2listw(socogal), verbose=FALSE)
summary(socoKP)

# Can also try estimating the lag model using a two-state-least-squares
# This is not an MLE estimator, so, again, we don't get likelihood score
# or AIC. We should anticipate different results than from the
# spatial lag model.  It too runs very quickly.

soco2SLS <- stsls(cpov ~ femhh + unem + hied,
	data=socotxt, nb2listw(socogal))
summary(soco2SLS)

# There's even an argument in this function call that gives us
# robust estimates that are adjusted for heteroskedasticity.  That is,
# there is a heteroskedasticity correction to the coefficients
# covariances:

soco2SLSR <- stsls(cpov ~ femhh + unem + hied, robust=TRUE,
	data=socotxt, nb2listw(socogal))
summary(soco2SLSR)

############################
#
# In the latest update of package spdep, we have access to a spatial
# model that includes both a lag and error component, sometimes
# called the SARAR model.  We fit this here using function sacsarlm:
#
###########################

soco.lag.error <- sacsarlm(cpov ~ femhh + unem + hied,
	data=socotxt, nb2listw(socogal), method = "eigen", quiet=FALSE)
summary(soco.lag.error)

# Okay.  Let's compare AICs:

AIC(reg1)            # -4106
AIC(soco.lag.eig)    # -4528
AIC(soco.err.eig)    # -4783
AIC(soco.lag.error)  # -4788
AIC(soco2SLS)        # 2SLS not a likelihood method
AIC(socoKP)          # Method of Moments not a likelihood method

# The soco.lag.error model has the lowest AIC, but not much lower
# than the error model.  Also, the lag parameter in the soco,lag.error
# model barely is significant at the 0.05 level.  What can we say
# about the error model estimated by GMM?  We may give preference to
# this model by keeping in mind the lack of normality in our OLS
# residuals.  Might encourage some preference for the GMM fit.

#####################################################################
#####
##### END OF DISCUSSION REGARDING SPATIAL REGRESSION MODELS
#####
#####################################################################

# Housekeeping:

ls()
rm(list=ls())
ls()

#####################################################################
#####################################################################
###
### END DEMO 4
###
#####################################################################
#####################################################################

